-- PharmaFlow staff accounts
-- Passwords are NOT stored here. Supabase Auth stores and verifies credentials.
create table if not exists public.staff (
    staff_id bigint generated by default as identity primary key,
    profile_id bigint not null references public.profiles(id) on delete cascade,
    auth_user_id uuid not null unique,
    full_name varchar(120) not null,
    address varchar(500),
    phone_number varchar(20),
    email varchar(160),
    profile_photo_url text,
    is_active boolean not null default true,
    last_login_at timestamptz,
    last_logout_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    constraint ck_staff_login_identifier check (
        email is not null or phone_number is not null
    )
);

create index if not exists ix_staff_profile_id
    on public.staff(profile_id);

create unique index if not exists ix_staff_profile_email
    on public.staff(profile_id, email)
    where email is not null;

create unique index if not exists ix_staff_profile_phone
    on public.staff(profile_id, phone_number)
    where phone_number is not null;

create index if not exists ix_staff_active_profile
    on public.staff(profile_id, is_active);
