CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- PharmaFlow billing / sales schema
-- Run once in Supabase SQL Editor before using Create Bill.
-- Selling prices are stored on product_batches.selling_unit_price.
-- Billing treats that retail selling price as GST-inclusive.

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    full_name VARCHAR(120) NULL,
    phone_number VARCHAR(20) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_customers_profile_id
    ON public.customers(profile_id);

CREATE INDEX IF NOT EXISTS ix_customers_profile_phone
    ON public.customers(profile_id, phone_number);

DROP TRIGGER IF EXISTS trg_customers_updated_at
    ON public.customers;

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON public.customers
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.sales_bills
(
    bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    customer_id BIGINT NULL REFERENCES public.customers(customer_id) ON DELETE SET NULL,
    bill_number VARCHAR(40) NOT NULL UNIQUE,
    customer_name VARCHAR(120) NULL,
    customer_phone VARCHAR(20) NULL,
    subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
    taxable_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    cgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(20) NOT NULL DEFAULT 'Cash',
    status VARCHAR(20) NOT NULL DEFAULT 'Completed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_sales_bills_amounts_nonnegative CHECK (
        subtotal >= 0 AND taxable_amount >= 0 AND
        cgst_amount >= 0 AND sgst_amount >= 0 AND
        igst_amount >= 0 AND gst_amount >= 0 AND total_amount >= 0
    ),
    CONSTRAINT ck_sales_bills_payment_method CHECK (
        payment_method IN ('Cash', 'UPI', 'Udhaar')
    ),
    CONSTRAINT ck_sales_bills_status CHECK (
        status IN ('Completed', 'Voided')
    )
);

CREATE INDEX IF NOT EXISTS ix_sales_bills_profile_created
    ON public.sales_bills(profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_sales_bills_profile_payment
    ON public.sales_bills(profile_id, payment_method);

CREATE TABLE IF NOT EXISTS public.sales_bill_items
(
    bill_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL REFERENCES public.sales_bills(bill_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(product_id) ON DELETE RESTRICT,
    batch_id BIGINT NOT NULL REFERENCES public.product_batches(batch_id) ON DELETE RESTRICT,
    product_name VARCHAR(200) NOT NULL,
    batch_number VARCHAR(100) NOT NULL,
    expiry_date DATE NOT NULL,
    quantity NUMERIC(12,2) NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    purchase_unit_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    mrp NUMERIC(14,2) NOT NULL,
    gst_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    taxable_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    cgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(14,2) NOT NULL DEFAULT 0,

    CONSTRAINT ck_sales_bill_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_sales_bill_items_prices_nonnegative CHECK (
        unit_price >= 0 AND purchase_unit_price >= 0 AND mrp >= 0
    ),
    CONSTRAINT ck_sales_bill_items_tax_nonnegative CHECK (
        gst_rate >= 0 AND taxable_amount >= 0 AND
        cgst_amount >= 0 AND sgst_amount >= 0 AND
        igst_amount >= 0 AND gst_amount >= 0 AND
        line_total >= 0
    )
);

CREATE INDEX IF NOT EXISTS ix_sales_bill_items_bill_id
    ON public.sales_bill_items(bill_id);

CREATE INDEX IF NOT EXISTS ix_sales_bill_items_product_id
    ON public.sales_bill_items(product_id);

CREATE INDEX IF NOT EXISTS ix_sales_bill_items_batch_id
    ON public.sales_bill_items(batch_id);

-- Quick verification
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('customers', 'sales_bills', 'sales_bill_items')
ORDER BY table_name;
