-- PharmaFlow customer account / Udhaar ledger
-- Run after Database/billing.sql in the Supabase SQL Editor.
-- Positive balance_change = customer owes the pharmacy.
-- Negative balance_change = the pharmacy owes the customer.

CREATE TABLE IF NOT EXISTS public.customer_ledger_entries
(
    ledger_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    customer_id BIGINT NOT NULL REFERENCES public.customers(customer_id) ON DELETE RESTRICT,
    bill_id BIGINT NULL REFERENCES public.sales_bills(bill_id) ON DELETE SET NULL,
    entry_type VARCHAR(40) NOT NULL,
    balance_change NUMERIC(14,2) NOT NULL,
    description VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_customer_ledger_entry_type CHECK (
        entry_type IN (
            'OpeningBalance',
            'UdhaarSale',
            'CustomerPayment',
            'PaymentToCustomer',
            'Adjustment'
        )
    ),
    CONSTRAINT ck_customer_ledger_balance_change CHECK (balance_change <> 0)
);

CREATE INDEX IF NOT EXISTS ix_customer_ledger_profile_customer_created
    ON public.customer_ledger_entries(profile_id, customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_customer_ledger_profile_created
    ON public.customer_ledger_entries(profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_customer_ledger_bill_id
    ON public.customer_ledger_entries(bill_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_ledger_udhaar_bill
    ON public.customer_ledger_entries(bill_id)
    WHERE bill_id IS NOT NULL
      AND entry_type = 'UdhaarSale';

-- Prevent duplicate customer phone records within the same pharmacy.
-- This intentionally allows NULL phone numbers.
CREATE UNIQUE INDEX IF NOT EXISTS ux_customers_profile_phone
    ON public.customers(profile_id, phone_number)
    WHERE phone_number IS NOT NULL;

-- Backfill existing Udhaar bills once, so previously generated credit bills
-- also appear in Manage Customer.
INSERT INTO public.customer_ledger_entries
(
    profile_id,
    customer_id,
    bill_id,
    entry_type,
    balance_change,
    description,
    created_at
)
SELECT
    bill.profile_id,
    bill.customer_id,
    bill.bill_id,
    'UdhaarSale',
    bill.total_amount,
    CONCAT('Udhaar sale · Bill ', bill.bill_number),
    bill.created_at
FROM public.sales_bills AS bill
WHERE bill.payment_method = 'Udhaar'
  AND bill.status = 'Completed'
  AND bill.customer_id IS NOT NULL
ON CONFLICT DO NOTHING;

-- Verification
SELECT
    COUNT(*) AS ledger_entries,
    COALESCE(SUM(CASE WHEN balance_change > 0 THEN balance_change ELSE 0 END), 0) AS positive_entries,
    COALESCE(SUM(CASE WHEN balance_change < 0 THEN ABS(balance_change) ELSE 0 END), 0) AS negative_entries
FROM public.customer_ledger_entries;
