-- PharmaFlow customer product request / reminder tracking
-- Run after Database/billing.sql and Database/customer-ledger.sql.
-- This table stores customer requests separately from inventory.
-- A reminder never changes stock and does not reserve a product.

CREATE TABLE IF NOT EXISTS public.customer_reminders
(
    reminder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    customer_id BIGINT NOT NULL REFERENCES public.customers(customer_id) ON DELETE CASCADE,

    -- India Medicine API selections may use catalog_id.
    -- OpenFDA/Open Food Facts selections stay live-source references.
    catalog_id BIGINT NULL REFERENCES public.product_catalog(catalog_id) ON DELETE SET NULL,
    product_source VARCHAR(50) NULL,
    product_external_id VARCHAR(160) NULL,

    -- Snapshot the product details so the reminder remains readable
    -- even if an external API later changes or removes the result.
    product_name VARCHAR(200) NOT NULL,
    generic_name VARCHAR(500) NULL,
    brand_name VARCHAR(160) NULL,
    manufacturer VARCHAR(200) NULL,
    dosage_form VARCHAR(100) NULL,
    strength VARCHAR(100) NULL,
    pack_size VARCHAR(100) NULL,
    barcode VARCHAR(100) NULL,

    note VARCHAR(500) NULL,
    reminder_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_customer_reminders_product_name
        CHECK (length(trim(product_name)) > 0),
    CONSTRAINT ck_customer_reminders_status
        CHECK (status IN ('Pending', 'Ordered', 'Completed', 'Cancelled')),
    CONSTRAINT ck_customer_reminders_source_pair
        CHECK (
            (product_source IS NULL AND product_external_id IS NULL)
            OR
            (product_source IS NOT NULL AND product_external_id IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS ix_customer_reminders_profile_customer_status
    ON public.customer_reminders(profile_id, customer_id, status);

CREATE INDEX IF NOT EXISTS ix_customer_reminders_profile_date_status
    ON public.customer_reminders(profile_id, reminder_date, status);

CREATE INDEX IF NOT EXISTS ix_customer_reminders_profile_product
    ON public.customer_reminders(profile_id, product_name);

DROP TRIGGER IF EXISTS trg_customer_reminders_updated_at
    ON public.customer_reminders;

CREATE TRIGGER trg_customer_reminders_updated_at
BEFORE UPDATE ON public.customer_reminders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- Safe upgrade for existing installations where the table was created earlier.
ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS catalog_id BIGINT NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS product_source VARCHAR(50) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS product_external_id VARCHAR(160) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS generic_name VARCHAR(500) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS brand_name VARCHAR(160) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(200) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS dosage_form VARCHAR(100) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS strength VARCHAR(100) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS pack_size VARCHAR(100) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS barcode VARCHAR(100) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS note VARCHAR(500) NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS reminder_date DATE NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'Pending';

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ NULL;

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE public.customer_reminders
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS ix_customer_reminders_profile_customer_status
    ON public.customer_reminders(profile_id, customer_id, status);

CREATE INDEX IF NOT EXISTS ix_customer_reminders_profile_date_status
    ON public.customer_reminders(profile_id, reminder_date, status);

CREATE INDEX IF NOT EXISTS ix_customer_reminders_profile_product
    ON public.customer_reminders(profile_id, product_name);

-- Verification
SELECT
    COUNT(*) AS reminder_count,
    COUNT(*) FILTER (WHERE status = 'Pending') AS pending_count,
    COUNT(*) FILTER (WHERE status = 'Ordered') AS ordered_count,
    COUNT(*) FILTER (WHERE status = 'Completed') AS completed_count,
    COUNT(*) FILTER (WHERE status = 'Cancelled') AS cancelled_count
FROM public.customer_reminders;
