-- PharmaFlow global product catalog cache
-- Run once in Supabase SQL Editor.
--
-- IMPORTANT:
-- 1. This table is ONLY a cache for results from the India Medicine API.
-- 2. PharmaFlow does NOT bulk-import the full medicine dataset.
-- 3. Search results are cached for a limited period. Referenced products are retained.
-- 4. OpenFDA and Open Food Facts are queried live and are NOT stored here.

CREATE TABLE IF NOT EXISTS public.product_catalog
(
    catalog_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(50) NOT NULL DEFAULT 'india-medicine-api',
    external_id VARCHAR(160) NOT NULL,
    product_type VARCHAR(40) NOT NULL DEFAULT 'medicine',

    product_name VARCHAR(200) NOT NULL,
    generic_name VARCHAR(500) NULL,
    brand_name VARCHAR(160) NULL,
    manufacturer VARCHAR(200) NULL,
    dosage_form VARCHAR(100) NULL,
    strength VARCHAR(100) NULL,
    pack_size VARCHAR(100) NULL,
    barcode VARCHAR(100) NULL,
    hsn_code VARCHAR(50) NULL,
    gst_rate NUMERIC(5,2) NULL,
    is_prescription_required BOOLEAN NOT NULL DEFAULT FALSE,

    source_url VARCHAR(500) NULL,

    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cache_expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_product_catalog_source_external
        UNIQUE (source, external_id),

    CONSTRAINT ck_product_catalog_source
        CHECK (source = 'india-medicine-api'),

    CONSTRAINT ck_product_catalog_gst_rate
        CHECK (gst_rate IS NULL OR (gst_rate >= 0 AND gst_rate <= 100))
);

-- Idempotent upgrades for an already-created product_catalog table.
ALTER TABLE public.product_catalog
    ADD COLUMN IF NOT EXISTS cache_expires_at
    TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days');

ALTER TABLE public.product_catalog
    ALTER COLUMN source SET DEFAULT 'india-medicine-api';

-- If the earlier implementation stored OpenFDA/Open Food Facts rows,
-- detach those catalog links from pharmacy products before enforcing the
-- India-only catalog rule.
UPDATE public.products
SET catalog_id = NULL
WHERE catalog_id IN
(
    SELECT catalog_id
    FROM public.product_catalog
    WHERE source <> 'india-medicine-api'
);

DELETE FROM public.product_catalog
WHERE source <> 'india-medicine-api';

ALTER TABLE public.product_catalog
    DROP CONSTRAINT IF EXISTS ck_product_catalog_source;

ALTER TABLE public.product_catalog
    ADD CONSTRAINT ck_product_catalog_source
    CHECK (source = 'india-medicine-api');

CREATE INDEX IF NOT EXISTS ix_product_catalog_barcode
    ON public.product_catalog(barcode);

CREATE INDEX IF NOT EXISTS ix_product_catalog_product_name
    ON public.product_catalog(product_name);

CREATE INDEX IF NOT EXISTS ix_product_catalog_brand_name
    ON public.product_catalog(brand_name);

CREATE INDEX IF NOT EXISTS ix_product_catalog_cache_expires_at
    ON public.product_catalog(cache_expires_at);

ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS catalog_id BIGINT NULL;

ALTER TABLE public.products
    DROP CONSTRAINT IF EXISTS fk_products_catalog;

ALTER TABLE public.products
    ADD CONSTRAINT fk_products_catalog
    FOREIGN KEY (catalog_id)
    REFERENCES public.product_catalog(catalog_id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_products_catalog_id
    ON public.products(catalog_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_products_profile_catalog_id
    ON public.products(profile_id, catalog_id)
    WHERE catalog_id IS NOT NULL;
