-- PharmaFlow global product catalog
-- Run once in Supabase SQL Editor before using:
-- Inventory -> + Add Item -> Search Product from All Products.
--
-- The catalog stores normalized reference data returned by external providers.
-- Stock quantity, batch number, expiry, purchase price and MRP remain pharmacy-specific
-- in products / product_batches.

CREATE TABLE IF NOT EXISTS public.product_catalog
(
    catalog_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(50) NOT NULL,
    external_id VARCHAR(160) NOT NULL,
    product_type VARCHAR(40) NOT NULL DEFAULT 'product',

    product_name VARCHAR(200) NOT NULL,
    generic_name VARCHAR(500) NULL,
    brand_name VARCHAR(160) NULL,
    manufacturer VARCHAR(200) NULL,
    dosage_form VARCHAR(100) NULL,
    strength VARCHAR(100) NULL,
    pack_size VARCHAR(100) NULL,
    barcode VARCHAR(100) NULL,
    hsn_code VARCHAR(50) NULL,
    gst_rate NUMERIC(5,2) NULL,
    is_prescription_required BOOLEAN NOT NULL DEFAULT FALSE,

    source_url VARCHAR(500) NULL,

    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_product_catalog_source_external
        UNIQUE (source, external_id),

    CONSTRAINT ck_product_catalog_gst_rate
        CHECK (gst_rate IS NULL OR (gst_rate >= 0 AND gst_rate <= 100))
);

CREATE INDEX IF NOT EXISTS ix_product_catalog_barcode
    ON public.product_catalog(barcode);

CREATE INDEX IF NOT EXISTS ix_product_catalog_product_name
    ON public.product_catalog(product_name);

CREATE INDEX IF NOT EXISTS ix_product_catalog_brand_name
    ON public.product_catalog(brand_name);

CREATE INDEX IF NOT EXISTS ix_product_catalog_last_synced_at
    ON public.product_catalog(last_synced_at DESC);

ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS catalog_id BIGINT NULL;

ALTER TABLE public.products
    DROP CONSTRAINT IF EXISTS fk_products_catalog;

ALTER TABLE public.products
    ADD CONSTRAINT fk_products_catalog
    FOREIGN KEY (catalog_id)
    REFERENCES public.product_catalog(catalog_id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_products_catalog_id
    ON public.products(catalog_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_products_profile_catalog_id
    ON public.products(profile_id, catalog_id)
    WHERE catalog_id IS NOT NULL;
