-- PharmaFlow - Invoice capture staging and audit tables
-- Run this script once in the Supabase PostgreSQL SQL editor.
-- It does not store the invoice image. Raw OCR text is temporary and is
-- cleared by the application after a successful stock save.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.invoice_imports
(
    import_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    source_type VARCHAR(20) NOT NULL DEFAULT 'upload',
    raw_ocr_text TEXT NULL,
    ocr_confidence NUMERIC(5,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    error_message VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_invoice_imports_profile
        FOREIGN KEY (profile_id)
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_invoice_imports_source_type
        CHECK (source_type IN ('camera', 'upload', 'pdf')),

    CONSTRAINT ck_invoice_imports_status
        CHECK (status IN ('draft', 'saved', 'failed')),

    CONSTRAINT ck_invoice_imports_ocr_confidence
        CHECK (ocr_confidence >= 0 AND ocr_confidence <= 100)
);

CREATE INDEX IF NOT EXISTS ix_invoice_imports_profile_id
    ON public.invoice_imports(profile_id);

CREATE INDEX IF NOT EXISTS ix_invoice_imports_profile_status
    ON public.invoice_imports(profile_id, status);

CREATE INDEX IF NOT EXISTS ix_invoice_imports_created_at
    ON public.invoice_imports(created_at DESC);

DROP TRIGGER IF EXISTS trg_invoice_imports_updated_at
    ON public.invoice_imports;

CREATE TRIGGER trg_invoice_imports_updated_at
BEFORE UPDATE ON public.invoice_imports
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.invoice_import_items
(
    import_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    raw_line TEXT NULL,
    product_name VARCHAR(200) NOT NULL DEFAULT '',
    batch_number VARCHAR(100) NOT NULL DEFAULT '',
    expiry_date DATE NULL,
    quantity NUMERIC(12,2) NULL,
    confidence NUMERIC(5,2) NOT NULL DEFAULT 0,
    validation_status VARCHAR(20) NOT NULL DEFAULT 'needs_review',
    validation_message VARCHAR(500) NULL,
    matched_product_id BIGINT NULL,
    saved_batch_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_invoice_import_items_import
        FOREIGN KEY (import_id)
        REFERENCES public.invoice_imports(import_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_invoice_import_items_product
        FOREIGN KEY (matched_product_id)
        REFERENCES public.products(product_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_invoice_import_items_batch
        FOREIGN KEY (saved_batch_id)
        REFERENCES public.product_batches(batch_id)
        ON DELETE SET NULL,

    CONSTRAINT uq_invoice_import_items_row
        UNIQUE (import_id, row_number),

    CONSTRAINT ck_invoice_import_items_quantity
        CHECK (quantity IS NULL OR quantity > 0),

    CONSTRAINT ck_invoice_import_items_confidence
        CHECK (confidence >= 0 AND confidence <= 100),

    CONSTRAINT ck_invoice_import_items_status
        CHECK (validation_status IN ('needs_review', 'ready', 'saved', 'removed'))
);

CREATE INDEX IF NOT EXISTS ix_invoice_import_items_import_id
    ON public.invoice_import_items(import_id);

CREATE INDEX IF NOT EXISTS ix_invoice_import_items_product_id
    ON public.invoice_import_items(matched_product_id);

CREATE INDEX IF NOT EXISTS ix_invoice_import_items_saved_batch_id
    ON public.invoice_import_items(saved_batch_id);

DROP TRIGGER IF EXISTS trg_invoice_import_items_updated_at
    ON public.invoice_import_items;

CREATE TRIGGER trg_invoice_import_items_updated_at
BEFORE UPDATE ON public.invoice_import_items
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- Quick verification
SELECT
    table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('invoice_imports', 'invoice_import_items')
ORDER BY table_name;



-- Purchase metadata required by the Purchase screen.
ALTER TABLE public.invoice_imports
    ADD COLUMN IF NOT EXISTS distributor_name VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS invoice_date DATE NULL,
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(14,2) NULL;

ALTER TABLE public.invoice_import_items
    ADD COLUMN IF NOT EXISTS mrp NUMERIC(14,2) NULL;

CREATE INDEX IF NOT EXISTS ix_invoice_imports_profile_distributor
    ON public.invoice_imports(profile_id, distributor_name);

CREATE INDEX IF NOT EXISTS ix_invoice_imports_profile_invoice_date
    ON public.invoice_imports(profile_id, invoice_date);
