-- PharmaFlow Reorder List
-- Run once in the Supabase SQL Editor before using the Reorder page.

CREATE TABLE IF NOT EXISTS public.reorder_list_items
(
    reorder_list_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
    quantity_when_added NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (quantity_when_added >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_reorder_list_items_profile_product UNIQUE (profile_id, product_id)
);

CREATE INDEX IF NOT EXISTS ix_reorder_list_items_profile_created
    ON public.reorder_list_items(profile_id, created_at DESC);
