-- PharmaFlow Reorder List
-- Run once in the Supabase SQL Editor. This is safe for both new and existing tables.

CREATE TABLE IF NOT EXISTS public.reorder_list_items
(
    reorder_list_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    product_id BIGINT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
    catalog_id BIGINT NULL,
    source VARCHAR(50) NULL,
    external_id VARCHAR(160) NULL,
    product_name VARCHAR(200) NULL,
    generic_name VARCHAR(500) NULL,
    brand_name VARCHAR(160) NULL,
    barcode VARCHAR(100) NULL,
    quantity_when_added NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (quantity_when_added >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_reorder_list_items_profile_product UNIQUE (profile_id, product_id)
);

-- Upgrade existing tables created by the first Reorder List release.
ALTER TABLE public.reorder_list_items
    ALTER COLUMN product_id DROP NOT NULL;

ALTER TABLE public.reorder_list_items
    ADD COLUMN IF NOT EXISTS catalog_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS source VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS external_id VARCHAR(160) NULL,
    ADD COLUMN IF NOT EXISTS product_name VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS generic_name VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS brand_name VARCHAR(160) NULL,
    ADD COLUMN IF NOT EXISTS barcode VARCHAR(100) NULL;

-- The filtered index below now enforces uniqueness for inventory-backed rows
-- without indexing the multiple NULL product_id values used by catalog-only rows.
ALTER TABLE public.reorder_list_items
    DROP CONSTRAINT IF EXISTS uq_reorder_list_items_profile_product;

-- One inventory-backed reorder record per product for each profile.
CREATE UNIQUE INDEX IF NOT EXISTS ux_reorder_list_items_profile_product
    ON public.reorder_list_items(profile_id, product_id)
    WHERE product_id IS NOT NULL;

-- One catalog-only reorder record per source/external product key.
CREATE UNIQUE INDEX IF NOT EXISTS ux_reorder_list_items_profile_catalog
    ON public.reorder_list_items(profile_id, source, external_id)
    WHERE product_id IS NULL AND source IS NOT NULL AND external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_reorder_list_items_profile_created
    ON public.reorder_list_items(profile_id, created_at DESC);
